# Generated by Django 2.2.3 on 2019-08-01 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_go_work', models.DateTimeField(auto_now_add=True, verbose_name='출근시간')),
                ('registered_off_work', models.DateTimeField(auto_now_add=True, verbose_name='퇴근시간')),
                ('commuter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Uniuser', verbose_name='기록자')),
            ],
            options={
                'verbose_name': '유니포인트 인턴업 출퇴근 기록부',
                'verbose_name_plural': '유니포인트 출퇴근 기록부',
                'db_table': 'inturnup_commute',
            },
        ),
    ]
